[build]
  publish = "dist"
  command = "npm run build"

# Set environment variables
[build.environment]
  VITE_STANDALONE_MODE = "true"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
